[package]
name = "rubber-docker"
version = "0.1.0"
authors = ["Piotr Roslaniec <p.roslaniec@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.15"
uuid = { version = "0.7", features = ["v4"] }
tar = "0.4.22"
nix = "0.13.0"